package org.bcn0.memfoo;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table CARD.
 */
public class Card {

    private Long id;
    private String kanji;
    private String kana;
    private String meaning;
    private String audio;
    private java.util.Date due;
    private java.util.Date introduced;
    private Integer correct;

    public Card() {
    }

    public Card(Long id) {
        this.id = id;
    }

    public Card(Long id, String kanji, String kana, String meaning, String audio, java.util.Date due, java.util.Date introduced, Integer correct) {
        this.id = id;
        this.kanji = kanji;
        this.kana = kana;
        this.meaning = meaning;
        this.audio = audio;
        this.due = due;
        this.introduced = introduced;
        this.correct = correct;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getKanji() {
        return kanji;
    }

    public void setKanji(String kanji) {
        this.kanji = kanji;
    }

    public String getKana() {
        return kana;
    }

    public void setKana(String kana) {
        this.kana = kana;
    }

    public String getMeaning() {
        return meaning;
    }

    public void setMeaning(String meaning) {
        this.meaning = meaning;
    }

    public String getAudio() {
        return audio;
    }

    public void setAudio(String audio) {
        this.audio = audio;
    }

    public java.util.Date getDue() {
        return due;
    }

    public void setDue(java.util.Date due) {
        this.due = due;
    }

    public java.util.Date getIntroduced() {
        return introduced;
    }

    public void setIntroduced(java.util.Date introduced) {
        this.introduced = introduced;
    }

    public Integer getCorrect() {
        return correct;
    }

    public void setCorrect(Integer correct) {
        this.correct = correct;
    }

}
